[T880] Travis CI- Configuration.
qrtl/nrq-custom pull request #169
Opened 2020-04-09 10:47 UTC by YogeshMahera-SerpentCS

Task #[880](https://www.quartile.co/web#id=880&action=771&model=project.task&view_type=form&menu_id=505)

2020-04-15 03:44 UTC, TimLai125 requested changes

2020-04-15 03:44 UTC, TimLai125 commented on .travis.yml
> +    # QRTL: Add following tests the installation of all modules including those are excluded
Comment out L72-L78

2020-04-15 03:44 UTC, TimLai125 commented on .travis.yml
> +    - EXCLUDE="partner_category_hierarchy,website_forum_visibility"
We do not need exclude for nrq-custom

2020-04-15 16:24 UTC, YogeshMahera-SerpentCS commented
Hi @TimLai125 Changes Amended

2020-04-16 16:11 UTC, YogeshMahera-SerpentCS commented
Hi @TimLai125 It's green can you check this?

2020-04-17 02:13 UTC, merged