[10.0][FIX] Removed total hour attandance from button
qrtl/nrq-custom pull request #176
Opened 2020-04-30 12:56 UTC by YogeshMahera-SerpentCS

- Task #[932](https://www.quartile.co/web#view_type=form&model=project.task&id=932&active_id=932&menu_id=)

2020-04-30 13:30 UTC, yostashiro approved these changes
LGTM!

Please bump the version to "10.0.1.3.1", and proceed with the rest of the steps.

2020-05-04 01:27 UTC, TimLai125 commented
@YogeshMahera-SerpentCS Please bump the version of this module https://github.com/qrtl/nrq-custom/blob/7294761d9eb203c9ff8cd890034ddce463339d6a/hr_attendance_timesheet_adj/__manifest__.py#L9

2020-05-04 08:24 UTC, TimLai125 requested changes

2020-05-04 08:24 UTC, TimLai125 commented on hr_timesheet_adj/__manifest__.py
> +    "version": "10.0.1.3.1",
@YogeshMahera-SerpentCS Please revert this change

2020-05-04 08:26 UTC, YogeshMahera-SerpentCS commented
@TimLai125 Amended changes

2020-05-04 08:31 UTC, TimLai125 approved these changes

2020-05-04 08:39 UTC, merged