[IMP] Add qualifications to employee
qrtl/nrq-custom pull request #177
Opened 2020-05-05 05:36 UTC by TimLai125

2020-05-05 08:02 UTC, yostashiro requested changes

2020-05-05 08:02 UTC, yostashiro commented on l10n_jp_hr_employee/i18n/ja.po
> +msgstr "持ち資格"
```suggestion
msgid "Acquired Qualifications"
msgstr "取得済資格"
```

2020-05-05 08:02 UTC, yostashiro commented on l10n_jp_hr_employee/models/hr_employee.py
> +        string='Qualification',
```suggestion
        string='Qualifications',
```

2020-05-05 08:02 UTC, yostashiro commented on l10n_jp_hr_employee/security/hr_security.xml
> -    </record>
We can't do this given that the qualification model keeps attachments with sensitive info. What we may need to do is to create another model that casts over the qualification names and make a one2many relationship to that model.

2020-05-05 08:02 UTC, yostashiro commented on l10n_jp_hr_employee/views/hr_employee_views.xml
> +                    <field name="qualification_ids" string="Acquired Qualification" widget="many2many_tags"/>
```suggestion
                    <field name="qualification_ids" string="Acquired Qualifications" widget="many2many_tags"/>
```

2020-05-06 02:27 UTC, TimLai125 commented on l10n_jp_hr_employee/security/hr_security.xml
> -    </record>
Added a new compute field to `hr.employee` to retrieve the names of the qualifications.

2020-05-07 03:06 UTC, yostashiro approved these changes
LGTM!

2020-05-07 03:39 UTC, merged