[10.0][T69][ADD/IMP]: Check in/Check out attendance entry in auditlog based on tz
qrtl/nrq-custom pull request #180
Opened 2020-05-18 06:09 UTC by YogeshMahera-SerpentCS

- TASK #[69](https://www.quartile.co/web#id=69&action=771&model=project.task&view_type=form&menu_id=505)

2020-05-18 07:35 UTC, YogeshMahera-SerpentCS commented
Hi @TimLai125 can you please review it?

2020-05-19 02:46 UTC, yostashiro requested changes
@YogeshMahera-SerpentCS Can we use context_timestamp() for the main part of your logic?

Please also update the description of the manifest file to add note to pay attention to the superuser's timezone setting.

2020-05-20 02:46 UTC, TimLai125 requested changes

2020-05-20 02:46 UTC, TimLai125 commented on auditlog_ext_nrq/__manifest__.py
> +    "description": """
description is deprecated, we should put it to the readme

2020-05-20 02:46 UTC, TimLai125 commented on auditlog_ext_nrq/models/auditlog_log.py
> +class AuditlogLogLine(models.Model):
We should create a new python for this class, i.e. auditlog_log_line

2020-05-21 07:40 UTC, TimLai125 commented
Please help to update the license to LGPL

2020-05-21 09:44 UTC, TimLai125 requested changes

2020-05-21 09:44 UTC, TimLai125 commented on auditlog_ext_nrq/readme/DESCRIPTION.rst
> +  * Allows to user can check the audit log entry based on user timezone only for datetime field.
Please re-generate the readme documents (index.html etc.)

2020-05-22 02:27 UTC, TimLai125 approved these changes

2020-05-27 06:22 UTC, TimLai125 commented on auditlog_ext_nrq/models/auditlog_log.py
>  from odoo import api, fields, models
Add back the empty line above the import

2020-05-27 06:22 UTC, TimLai125 commented on auditlog_ext_nrq/models/auditlog_log_line.py
> +from odoo import api, fields, models
Add an empty line above the import

2020-05-27 06:22 UTC, TimLai125 commented on auditlog_ext_nrq/models/auditlog_log_line.py
> +# Copyright 2019 Quartile Limited
2020

2020-05-27 06:22 UTC, TimLai125 commented on auditlog_ext_nrq/models/auditlog_log.py
>  # Copyright 2019 Quartile Limited
2019-2020

2020-05-27 06:22 UTC, TimLai125 commented on auditlog_ext_nrq/__manifest__.py
>  # Copyright 2019 Quartile Limited
2019-2020

2020-05-27 06:24 UTC, TimLai125 requested changes
Update to "Request Changes"

2020-05-27 09:48 UTC, YogeshMahera-SerpentCS commented
Hi @TimLai125 amended changes!

2020-06-01 06:42 UTC, merged