[10.0][T1019][FIX]:- Fix ACL issue and Added more test-cases.
qrtl/nrq-custom pull request #185
Opened 2020-06-08 05:15 UTC by YogeshMahera-SerpentCS

TASK[ #1019](https://www.quartile.co/web#view_type=form&model=project.task&id=1019&active_id=1019&menu_id=)

Steps to reproduce the error:-
1: Create Audit log rule for any object and subscribe for read access:
2: Log in with demo users or who have only employee access.
3: Try to read object value which is subscribed.
4: You will Get ACL Warning.

Expected:
Demo users/Users should be able to read the value which objects for they subscribed to.

Why it causes:
Demo users/Users try to create a log in the Audit log line which they don't have access.

2020-06-08 05:16 UTC, YogeshMahera-SerpentCS commented
Hi, @TimLai125  could you please review it?

2020-06-08 16:01 UTC, yostashiro commented on auditlog/models/rule.py
> +            rule_model.sudo().create_logs(
@YogeshMahera-SerpentCS Your PR to OCA already had this here https://github.com/OCA/server-tools/pull/1830/files#diff-e2cdd2f4b9da04f93936a15fa53fef79R258 and how did we miss it in this PR?

2020-06-12 06:19 UTC, TimLai125 requested changes

2020-06-12 06:19 UTC, TimLai125 commented on auditlog/tests/test_auditlog.py
> +        users = self.env['res.users'].search([])
Please try to read a demo record from `res.partner`

2020-07-27 02:39 UTC, merged