[1394][IMP]base_ir_values_security_adj: pre-commit, README
qrtl/nrq-custom pull request #211
Opened 2020-11-18 06:02 UTC by Ryoko04

Task [1394](https://www.quartile.co/web#id=1394&action=771&model=project.task&view_type=form&menu_id=505)

No changes.

2020-11-21 02:50 UTC, yostashiro reviewed
@Ryoko04 Please update the README to briefly explain WHY we need the changes done by this module.

2020-11-27 00:21 UTC, Ryoko04 commented
@yostashiro I added the description. Can you review it again?

2020-11-27 02:33 UTC, yostashiro requested changes

2020-11-27 02:33 UTC, yostashiro commented on base_ir_values_security_adj/readme/DESCRIPTION.rst
> +  * Add "Employee" group to the "Defaults: alter personal values only" (XML ID: base.ir_values_default_rule)  to restrict "Employee" group user to set default value for "Only you"
```suggestion
  * Adds "Employee" group to the "Defaults: alter personal values only" (XML ID: base.ir_values_default_rule).
  * Adds a new record rule "Defaults: alter all values" to which "Admin / Settings" group is assigned.

Without these adjustments, no one would be able to create user-defined defaults that were applicable for all users.
```

Let's try and address the background why we had to make these changes.

2020-11-27 06:13 UTC, yostashiro requested changes

2020-11-27 06:13 UTC, yostashiro commented on base_ir_values_security_adj/__manifest__.py
> +    "application": True,
```suggestion
```
Sorry, missed this one. We don't need this line. This module is not an "app."

2020-11-27 07:14 UTC, yostashiro approved these changes
LGTM 👍

2020-11-27 08:14 UTC, merged